name: Ask name and version

on:
  pull_request:

permissions:
  pull-requests: write
  contents: write

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check comment
        id: check_comment
        run: |
          COMMENT="Per creare la Model Card è necessario specificare il nome e la versione del modello all'interno del file name_version.yml, che si trova nella directory src/Data."
          PR_NUMBER=${{ github.event.pull_request.number }}

          COMMENTS_URL="https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          EXISTING_COMMENTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $COMMENTS_URL)

          CONTROL=true
          if echo "$EXISTING_COMMENTS" | grep -q "\"body\": \"$COMMENT\""; then
            echo "Comment already exists"
            CONTROL=false
            exit 1
          fi

          echo "::set-output name=comment_exists::$CONTROL"

      - name: Generate comment
        if: steps.check_comment.outputs.comment_exists == 'true'
        run: |
          COMMENT="Per creare la Model Card è necessario specificare il nome e la versione del modello all'interno del file **name_version.yml**, che si trova nella directory **src/Data**."
          PR_NUMBER=${{ github.event.pull_request.number }}
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            -d "{\"body\":\"$COMMENT\"}"

      - name: Create md files file
        run: |
          mkdir -p src/Data
          > src/Data/name_version.md
          > src/Data/_parts.md

      - name: Commit and push files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "created md files"
          git pull --rebase origin ${{ github.head_ref }}
          git push origin HEAD:${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


