name: Ask name and version

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check comment
        id: check_comment
        run: |
          COMMENT="Specificare il nome e la versione del modello di cui si vuole generare la Model Card"
          PR_NUMBER=${{ github.event.pull_request.number }}

          # Fetch existing comments
          COMMENTS_URL="https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
          EXISTING_COMMENTS=$(curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" $COMMENTS_URL)

          # Check if the comment already exists
          if echo "$EXISTING_COMMENTS" | grep -q "$COMMENT"; then
            exit 0
          fi

      - name: Generate comment
        run: |
          COMMENT="Specificare il nome e la versione del modello di cui si vuole generare la Model Card"
          PR_NUMBER=${{ github.event.pull_request.number }}
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
            -d "{\"body\":\"$COMMENT\"}"

