name: Post Comment

on:
  pull_request:

permissions:
  pull-requests: write

jobs:
  generate-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate comment
        run: |
          COMMENT="di quale modello si vuole generare la model card?"
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "PR Number: $PR_NUMBER"  # Verifica il numero della PR per debug
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/comments \
            -d "{\"body\":\"$COMMENT\"}"

