name: Comment Pull Request

on:
  issue_comment:
    types: [created, edited]

jobs:
  process_comment:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'

      # Extract the comment text
      - name: Extract comment text
        id: extract_comment
        run: |
          echo "${{ github.event.comment.body }}" > comment.txt
          echo "comment=$(<comment.txt)" >> $GITHUB_ENV

      # Run Python script with the extracted comment
      - name: Run Python script
        run: |
          python src/main.py "$comment"