name: Comment Pull Request

on:
  issue_comment:
    types: [created, edited]

jobs:
  echo_comment:
    runs-on: ubuntu-latest
    steps:
      - name: Print Comment
        run: |
          echo "Comment Body: ${{ github.event.comment.body }}"

