name: Comment on Pull Request

on:
  pull_request_comment:
    types: [created]

jobs:
  print_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Print comment content
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
