name: Comment on Pull Request

on:
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, reopened]

jobs:
  print_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Print comment content
        run: |
          echo "Comment: ${{ github.event.comment.body }}"
