name: Process name_version.md

on:
  pull_request:
    paths:
      - 'ModelCardsGenerator/Data/name_version.md'

permissions:
  pull-requests: write
  contents: write

jobs:
  modelcard_generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check if name_version.md exists and is not empty
        id: check
        run: |
          CONTROL=true
          if [ -f ModelCardsGenerator/Data/name_version.md ]; then
            CONTENT=$(cat ModelCardsGenerator/Data/name_version.md)
            if [ -z "$CONTENT" ]; then
              echo "File ModelCardsGenerator/Data/name_version.md is empty!"
              CONTROL=false
            fi
          else
            echo "File ModelCardsGenerator/Data/name_version.md not found!"
            CONTROL=false
          fi

          echo "::set-output name=file_exists::$CONTROL"

      - name: Set up Python
        if: steps.check.outputs.file_exists == 'true'
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        if: steps.check.outputs.file_exists == 'true'
        run: |
          pip install mlflow
          pip install jinja2

      - name: create Model Card using generator.py
        if: steps.check.outputs.file_exists == 'true'
        run: |     
          CONTENT=$(cat ModelCardsGenerator/Data/name_version.md)
          echo "passing content to generator.py"
          OUTPUT=$(python ModelCardsGenerator/src/generator.py "$(printf '%s' "$CONTENT")")

          if [ -n "$OUTPUT" ]; then
            echo "EXCEPTION in generator.py: $OUTPUT"

            COMMENT="Check name_version.md: $OUTPUT"
            PR_NUMBER=${{ github.event.pull_request.number }}
            PR_NUMBER=${{ github.event.pull_request.number }}
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
              -d "{\"body\":\"$COMMENT\"}"
          fi

      - name: Commit and push Model Card
        if: steps.check.outputs.file_exists == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          if [[ $(git status --porcelain ModelCards/) ]]; then
            echo "Changes detected in ModelCards, proceeding with commit and push."
            git add .
            git commit -m "Model Card generated"
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}

            COMMENT="Per completare la Model Card puoi specificare le informazioni aggiuntive all'interno del file _parts.md che si trova nella directory ModelCardsGenerator/Data."
            PR_NUMBER=${{ github.event.pull_request.number }}
            PR_NUMBER=${{ github.event.pull_request.number }}
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments \
              -d "{\"body\":\"$COMMENT\"}"

          else
            echo "No changes in ModelCards, skipping commit and push."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
